

import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}
pipeline {
  agent any
  environment {
    appName = "variable" 
  }
  stages {

 stage("Build and testing in maven"){
     
      steps {
          script {			
           sh "echo 'Examen de Construccion y evolucion'"
           sh "cd /var/lib/jenkins/workspace/Proyecto1B/src/main/resources"
           sh "ls -a"
           sh "java -cp /var/lib/jenkins/workspace/Proyecto1B/target/Calculadora_GR4-1.0-SNAPSHOT.jar:/var/lib/jenkins/workspace/Proyecto1B/src/main/resources/json.jar ec.edu.epn.Main"
           
        }
      }
    }
  }
  post {
      always {          
          deleteDir()
           sh "echo 'El proyecto se ha ejecutado'"
      }
      success {
            sh "echo 'Ejecucion exitosa'"
        }

      failure {
            sh "echo 'Fallo al ejecutar'"
      }
      
  }
} 
